- id: markdown-index-autogen
  name: Automatic generate / refresh markdown index
  description: Automatically generate / refresh markdown index with updated folder structure
  entry: python gen.py
  language: python
  types: [text]